/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstadoStateSlugRouteImport } from './routes/estado.$stateSlug'
import { Route as EstacionSplatRouteImport } from './routes/estacion.$'
import { Route as AdminIngestionRouteImport } from './routes/admin.ingestion'
import { Route as EstadoStateSlugMunicipalitySlugRouteImport } from './routes/estado.$stateSlug_.$municipalitySlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoStateSlugRoute = EstadoStateSlugRouteImport.update({
  id: '/estado/$stateSlug',
  path: '/estado/$stateSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstacionSplatRoute = EstacionSplatRouteImport.update({
  id: '/estacion/$',
  path: '/estacion/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestionRoute = AdminIngestionRouteImport.update({
  id: '/admin/ingestion',
  path: '/admin/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoStateSlugMunicipalitySlugRoute =
  EstadoStateSlugMunicipalitySlugRouteImport.update({
    id: '/estado/$stateSlug_/$municipalitySlug',
    path: '/estado/$stateSlug/$municipalitySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/metricas': typeof MetricasRoute
  '/og.png': typeof OgDotpngRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/estacion/$': typeof EstacionSplatRoute
  '/estado/$stateSlug': typeof EstadoStateSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/estado/$stateSlug/$municipalitySlug': typeof EstadoStateSlugMunicipalitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/metricas': typeof MetricasRoute
  '/og.png': typeof OgDotpngRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/estacion/$': typeof EstacionSplatRoute
  '/estado/$stateSlug': typeof EstadoStateSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/estado/$stateSlug/$municipalitySlug': typeof EstadoStateSlugMunicipalitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/metricas': typeof MetricasRoute
  '/og.png': typeof OgDotpngRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/estacion/$': typeof EstacionSplatRoute
  '/estado/$stateSlug': typeof EstadoStateSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/estado/$stateSlug_/$municipalitySlug': typeof EstadoStateSlugMunicipalitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/metricas'
    | '/og.png'
    | '/perfil'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sitemap.xml'
    | '/admin/ingestion'
    | '/estacion/$'
    | '/estado/$stateSlug'
    | '/api/auth/$'
    | '/estado/$stateSlug/$municipalitySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/metricas'
    | '/og.png'
    | '/perfil'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sitemap.xml'
    | '/admin/ingestion'
    | '/estacion/$'
    | '/estado/$stateSlug'
    | '/api/auth/$'
    | '/estado/$stateSlug/$municipalitySlug'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/explorar'
    | '/metricas'
    | '/og.png'
    | '/perfil'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sitemap.xml'
    | '/admin/ingestion'
    | '/estacion/$'
    | '/estado/$stateSlug'
    | '/api/auth/$'
    | '/estado/$stateSlug_/$municipalitySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  MetricasRoute: typeof MetricasRoute
  OgDotpngRoute: typeof OgDotpngRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerRoute: typeof RestablecerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminIngestionRoute: typeof AdminIngestionRoute
  EstacionSplatRoute: typeof EstacionSplatRoute
  EstadoStateSlugRoute: typeof EstadoStateSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EstadoStateSlugMunicipalitySlugRoute: typeof EstadoStateSlugMunicipalitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado/$stateSlug': {
      id: '/estado/$stateSlug'
      path: '/estado/$stateSlug'
      fullPath: '/estado/$stateSlug'
      preLoaderRoute: typeof EstadoStateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estacion/$': {
      id: '/estacion/$'
      path: '/estacion/$'
      fullPath: '/estacion/$'
      preLoaderRoute: typeof EstacionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingestion': {
      id: '/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado/$stateSlug_/$municipalitySlug': {
      id: '/estado/$stateSlug_/$municipalitySlug'
      path: '/estado/$stateSlug/$municipalitySlug'
      fullPath: '/estado/$stateSlug/$municipalitySlug'
      preLoaderRoute: typeof EstadoStateSlugMunicipalitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  MetricasRoute: MetricasRoute,
  OgDotpngRoute: OgDotpngRoute,
  PerfilRoute: PerfilRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerRoute: RestablecerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminIngestionRoute: AdminIngestionRoute,
  EstacionSplatRoute: EstacionSplatRoute,
  EstadoStateSlugRoute: EstadoStateSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EstadoStateSlugMunicipalitySlugRoute: EstadoStateSlugMunicipalitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
